parameters:
  jobeet_job.jobManager.class: Jobeet\JobBundle\Model\JobManager

services:
  jobeet_job.job_manager:
    class: %jobeet_job.jobManager.class%
    arguments: [ @doctrine.orm.entity_manager, %jobeet_job.default_active_days% ]
